### ISSUE TITLE
Problem of the Debug Version unity_decoder.exe

### ISSUE THREAD

**Issue by isombyt** [nevermoe/unity_metadata_loader#1]
You did a greate job on recovering symbols from the global-metadata.dat
The Debug version executable file compiled by VC2015 have some unusual dependence.
Could you please compile and upload a Release version Instead.

**Comment by nevermoe** [comment]
Hi, thank you for your request. Can you tell me what dependence is missing? I don't think I used any special library.

**Comment by isombyt** [comment]
I have just install a brand new VC2015 environment to get anything it need.
But it still missing APPCRT140D.DLL.And I can't find it anywhere.

nevermoe notifications@github.com于2016年9月30日周五 下午3:43写道：

**Comment by nevermoe** [comment]
Ok, it's strange. I will upload a release version later. Please wait a while.

**Comment by nevermoe** [comment]
Hi, I added a release build. Please have a try.

**Comment by isombyt** [comment]
I Recovery most of the method names, but just a little part of the StringLiterals recovered in metadataUsage.I wrote pure Python version to load symbols and found that only 328 of 11261 StringLiteral used in metadataUsage.That was so wired.
根本不知道global-metadata.dat里面的其他StringLiteral用去哪了。。

**Comment by nevermoe** [comment]
Sorry, I don't know what's your meaning. You wrote a pure python version of this plugin?

**Comment by isombyt** [comment]
Yes, I wrote such a plugin.To debug on my poor little Linux IDA And found
that not all of the StringLiteral registered to metaUsage , the same result
as the one you wrote in c++. And I'm trying to find out where the other
StringLiteral used,but still have no more ideas.

nevermoe notifications@github.com于2016年10月2日周日 下午5:33写道：

Sorry, I don't know what's your meaning. You wrote a pure python version of
this plugin?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/nevermoe/unity_metadata_loader/issues/1#issuecomment-250962542,
or mute the thread

**Comment by nevermoe** [comment]
g_metadataUsage isn't consisted of mere StringLiterals. It contains other info like TypeInfo and so on. I don't think those are important so I just ignore them.

**Comment by isombyt** [comment]
Oh, sure. I know about that. I am not focusing on g_metadata. I am looking
for other codes which use StringLiteral.

nevermoe notifications@github.com于2016年10月2日周日 下午6:27写道：
