### ISSUE TITLE
No module named ida_idp

### ISSUE THREAD

**Issue by ghost** [nevermoe/unity_metadata_loader#3]
I'm trying to load python script in IDA but i'm getting an error about "No module named ida_idp" (see screenshot). I followed the excat steps
I'm using Python 2.7.12 on Windows 10 x64

![image](https://cloud.githubusercontent.com/assets/20967118/21151475/ec07cd6e-c162-11e6-8345-17c4e5c8fc90.png)

**Comment by nevermoe** [comment]
hi, because maybe some lower version of IDA doesn't support this lib. You can checkout a previous commit of my code using 

`git checkout a784bcbd6995d0075f3eabbe5a4e0b5f9b8f70c5`

This previous version does not use the ida_idp lib but may have problem if you are working with a x86 binary. But it should work fine with arm.

**Comment by ghost** [comment]
Thanks, i will try to upgrade IDA to the latest version asap. I always working with ARM binary and not x86.

**Comment by Darkness0ut** [comment]
replace ida_idp with idaapi can use in ida 6.8.

**Comment by ghost** [comment]
Thanks but IDA is not loading any string 

```
Locating Methods and Strings...
Methods Start At: 12e80b8
Loading Symbols...
```

**Comment by ghost** [comment]
anyone can help? i can't upgrade IDA to 6.95

**Comment by nevermoe** [comment]
hi,  I can't suggest anything with your information. Can you confirm two text files outputted in the directory of your binary?  Besides, you should use 32bit ida with 32 bit binary and vice versa for 64 bit. Don't mix them up.

**Comment by ghost** [comment]
I tried 32 bit IDA but still not working. I don't know what you mean by two text files but this is my directory.

![image](https://cloud.githubusercontent.com/assets/20967118/21386402/f31e7312-c772-11e6-84af-9131bc2c5bbc.png)

**Comment by nevermoe** [comment]
It's strange because two .txt files should be created in this folder. You can try double click unity_decoder.exe to see if any .txt file is generated. It's probably that your binary is compiled by a incompitable unity version.

Tell me what does the unity_decoder.exe output in the cmd window.

**Comment by ghost** [comment]
Ok i found out. First, I place the unity_decoder.exe from the Release folder in the same directory, double-clicked and it worked, then load the script in IDA Pro.

unity_decoder.exe from Debug folder did not work because the ucrtbased.dll is missing. 

The reason why the script didn't execute the .exe file because Windows can't recognize the "/" in the path. In python I printed the path.

>>> import os, sys
>>> path = os.getcwd()
>>> test = (path+'/unity_decoder.exe')
>>> print test
D:\Android apps + data\censoredgame/unity_decoder.exe
>>> 

I don't know if you made the script cross-platform, but it would be great to make a OS check before setting the path. In Windows it must be \unity_decoder.exe i guess

**Comment by lHectorl** [comment]
i have the same problem and still cant make it work ive even installed 6.95 but nothing same problem
