### ISSUE TITLE
Function declaration is expected

### ISSUE THREAD

**Issue by parsifall** [nevermoe/unity_metadata_loader#5]
Everytime I run the script via File->Run Script an error appears: "...unity:loader.py,1: Function declaration is expected. Any hint?

**Comment by nevermoe** [comment]
You should use File->Script file. I don't see any menu named Run Script, so maybe you are using a too old IDA? Not sure, better to provide me a screenshot.

**Comment by parsifall** [comment]
I wrong, my mistake, I use File->Script file :/

**Comment by parsifall** [comment]
I mean I still get this error, I didn't resolve it :/

**Comment by pie3636** [comment]
Same error, using "File -> Script file" leads to the same error message. Using IDA Pro 7.0.170914 on W10.

Screenshot: https://i.imgur.com/7kd6pfl.png

**Comment by SfetcuIonica** [comment]
I've got the same error. I am using IDA Pro 7.3. Can someone who knows be kind enough to enlighten us what the problem is?

**Comment by cerealbocks** [comment]
i have the same error. i thnk the issue is that IDA is trying to load python64.dll but i have 32 bit IDA pro installed.

**Comment by xiufenyu** [comment]
Another possible reason is the python version. Please configure  python with version that your IDA recommends in the official website.
